export const COLORS = {
  background: '#FFFFFF',
  primary: '#2E7D32',
  secondary: '#8BC34A',
  card: '#F1F8E9',
  textPrimary: '#1B1B1B',
  textSecondary: '#4CAF50',
  border: '#C8E6C9',
  buttonPrimaryBg: '#2E7D32',
  buttonPrimaryText: '#FFFFFF',
  buttonSecondaryBorder: '#8BC34A',
  buttonSecondaryText: '#2E7D32',
  headerBg: '#2E7D32',
  headerText: '#FFFFFF',
  tabBarBg: '#FFFFFF',
  tabBarActive: '#2E7D32',
  tabBarInactive: '#A5D6A7',
  error: '#D32F2F',
  // Estados (módulo de autoevaluación)
  correcto: '#4CAF50',
  incorrecto: '#F44336',
  advertencia: '#FF9800',
  neutro: '#9E9E9E',
};
